# Generated by Django 4.1.1 on 2022-09-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_num',
            field=models.CharField(default='4', max_length=1),
        ),
    ]
