# Generated by Django 4.1.1 on 2022-09-29 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_sheet_sheet_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
