# Generated by Django 4.1.1 on 2022-09-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_sheet_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='id_number',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
