# Generated by Django 4.1.1 on 2022-09-29 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_alter_sheet_id_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheet',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Signup Sheet'},
        ),
        migrations.AddField(
            model_name='sheet',
            name='clues_solved',
            field=models.IntegerField(blank=True, null=True, verbose_name='Clues Solved'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='icon_found',
            field=models.IntegerField(blank=True, null=True, verbose_name='Icons Found'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='id_number',
            field=models.CharField(default='', max_length=8, unique=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_num',
            field=models.CharField(default='3', max_length=1, verbose_name='Sheet Number'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Date'),
        ),
    ]
