# Generated by Django 4.1.1 on 2022-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_sheet_options_sheet_clues_solved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='sheet_num',
            field=models.CharField(default='4', max_length=1, verbose_name='Sheet Number'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='start_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Start Date'),
        ),
    ]
